name: unlearning
channels:
  - defaults
dependencies:
  - pip=24.2
  - python=3.10
  - pip:
      - fsspec==2024.10.0
      - huggingface-hub==0.26.1
      - matplotlib==3.9.2
      - numpy==1.26.4
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - tensorflow==2.17.0
